POST http://localhost:8000/user/checkCode
Content-Type: application/json

{
  "encryptedCode": "Xo1eSMoUUIK7UYqMZZk/bOg8LZDxmiZPs5x0wVizw0V1MazD6MXgkSJzw77X4F6ffGeBxXdum/UXeySUzgbJLnkD5Mc4iSSjkIGbsZQpKA+p",
  "decryptedCode": "111204"
}